In [3]:
import numpy as np

In [5]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
a.shape

(3,)

In [8]:
a2=np.array ([[ 1,2,3], [4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [13]:
np.zeros ([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
a5=np.arange(0,60,5)
print(a5)

[ 0  5 10 15 20 25 30 35 40 45 50 55]


In [19]:
a3=np.array ([[ (1, 2,3), (4,5,6)], [(7,8,9), (10,11 ,12 )]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [49]:
a3.shape

(2, 2, 3)

In [26]:
a4=a3.reshape(3,3,2)
print(a4)

ValueError: cannot reshape array of size 12 into shape (3,3,2)

In [36]:
a6=a5.reshape(2,2,3)
print(a6)

[[[ 0  5 10]
  [15 20 25]]

 [[30 35 40]
  [45 50 55]]]


In [38]:
a6.shape

(2, 2, 3)

In [43]:
a[-2]

2

In [48]:
a2[1,1:3]

array([5, 6])

In [51]:
a3[1,0,0]

7

In [52]:
import pandas as pd

In [53]:
df= pd.DataFrame({"a" : [4 ,5, 6], "b" : [7, 8, 9], "c" : [10, 11, 12]},index = [1, 2, 3])

In [54]:
print(df)

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12


In [58]:
df.tail(1)

a  b   c
3  6  9  12

In [59]:
df.head()

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [60]:
df1= pd.DataFrame([[4, 7, 10],[5, 8, 11], [6, 9, 12]], index=[1, 2, 3],columns=['a', 'b', 'c'])

In [61]:
df1.head()

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [62]:
df2= pd.DataFrame({"a" : [4 ,5, 6], "b" : [7, 8, 9], "c" : [10, 11,12]}, index = pd.MultiIndex.from_tuples([('d',1),('d',2),('e',2)],names=['n','v']))

In [63]:
df2.head()

a  b   c
n v          
d 1  4  7  10
  2  5  8  11
e 2  6  9  12

In [64]:
pd.melt(df)

variable  value
0        a      4
1        a      5
2        a      6
3        b      7
4        b      8
5        b      9
6        c     10
7        c     11
8        c     12

In [65]:
df.head()

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [66]:
pd.concat([df,df1])

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12
1  4  7  10
2  5  8  11
3  6  9  12

In [67]:
pd.concat([df,df2])

a  b   c
1       4  7  10
2       5  8  11
3       6  9  12
(d, 1)  4  7  10
(d, 2)  5  8  11
(e, 2)  6  9  12

In [68]:
pd.concat([df,df1],axis=1)

a  b   c  a  b   c
1  4  7  10  4  7  10
2  5  8  11  5  8  11
3  6  9  12  6  9  12

In [73]:
df3=pd.concat([df,df2],axis=1)
df3.head(6)

a    b     c    a    b     c
1       4.0  7.0  10.0  NaN  NaN   NaN
2       5.0  8.0  11.0  NaN  NaN   NaN
3       6.0  9.0  12.0  NaN  NaN   NaN
(d, 1)  NaN  NaN   NaN  4.0  7.0  10.0
(d, 2)  NaN  NaN   NaN  5.0  8.0  11.0
(e, 2)  NaN  NaN   NaN  6.0  9.0  12.0

In [78]:
df.sort_values('a',ascending=False)

a  b   c
3  6  9  12
2  5  8  11
1  4  7  10

In [80]:
df.rename(columns={'a':'A','b':'B','c':'C'})

A  B   C
1  4  7  10
2  5  8  11
3  6  9  12

In [81]:
df.head()

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [82]:
df.drop(columns=['a','c'])

b
1  7
2  8
3  9