In [2]:
import numpy as np

In [3]:
a=np.array ([1,2,3])
print(a)

[1 2 3]


In [6]:
b=np.array ([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [9]:
c=np.array ([[ (1, 2,3), (4,5,6)], [(7,8,9), (10,11 ,12 )]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [10]:
c.shape

(2, 2, 3)

In [15]:
z=np.zeros([3,4])
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
r=np.arange(0,60,5)
print(r)

[ 0  5 10 15 20 25 30 35 40 45 50 55]


In [22]:
r.reshape(2,2,3)

array([[[ 0,  5, 10],
        [15, 20, 25]],

       [[30, 35, 40],
        [45, 50, 55]]])

In [39]:
r1=r.reshape(3,2,2)
r1

array([[[ 0,  5],
        [10, 15]],

       [[20, 25],
        [30, 35]],

       [[40, 45],
        [50, 55]]])

In [26]:
a[0]

1

In [31]:
b[1,1]

5

In [32]:
c[0,0,0]

1

In [33]:
c[1,0,0]

7

In [34]:
a[:]

array([1, 2, 3])

In [36]:
a[0:2]

array([1, 2])

In [37]:
b[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [38]:
b[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [40]:
r1[1:3,0:2,0]

array([[20, 30],
       [40, 50]])

In [41]:
import pandas as pd

In [42]:
df= pd.DataFrame({"a" : [4 ,5, 6], "b" : [7, 8, 9], "c" : [10, 11, 12]},index = [1, 2, 3])

In [43]:
print(df)

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12


In [46]:
df.head(1)

a  b   c
1  4  7  10

In [47]:
df.tail(2)

a  b   c
2  5  8  11
3  6  9  12

In [48]:
df1= pd.DataFrame([[4, 7, 10],[5, 8, 11], [6, 9, 12]], index=[1, 2, 3],columns=['a', 'b', 'c'])

In [49]:
print(df1)

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12


In [50]:
df3= pd.DataFrame({"a" : [4 ,5, 6], "b" : [7, 8, 9], "c" : [10, 11,12]}, index = pd.MultiIndex.from_tuples([('d',1),('d',2),('e',2)],names=['n','v']))

In [51]:
print(df3)

     a  b   c
n v          
d 1  4  7  10
  2  5  8  11
e 2  6  9  12


In [52]:
df3.head()

a  b   c
n v          
d 1  4  7  10
  2  5  8  11
e 2  6  9  12

In [53]:
pd.melt(df)

variable  value
0        a      4
1        a      5
2        a      6
3        b      7
4        b      8
5        b      9
6        c     10
7        c     11
8        c     12

In [54]:
pd.melt(df3)

variable  value
0        a      4
1        a      5
2        a      6
3        b      7
4        b      8
5        b      9
6        c     10
7        c     11
8        c     12

In [55]:
pd.concat([df,df3])

a  b   c
1       4  7  10
2       5  8  11
3       6  9  12
(d, 1)  4  7  10
(d, 2)  5  8  11
(e, 2)  6  9  12

In [56]:
pd.concat([df,df3],axis=1)

a    b     c    a    b     c
1       4.0  7.0  10.0  NaN  NaN   NaN
2       5.0  8.0  11.0  NaN  NaN   NaN
3       6.0  9.0  12.0  NaN  NaN   NaN
(d, 1)  NaN  NaN   NaN  4.0  7.0  10.0
(d, 2)  NaN  NaN   NaN  5.0  8.0  11.0
(e, 2)  NaN  NaN   NaN  6.0  9.0  12.0

In [58]:
df.sort_values('a',ascending=False)

a  b   c
3  6  9  12
2  5  8  11
1  4  7  10