In [1]:
import numpy as np

In [2]:
N1=np.array([1,2,3])
N1

array([1, 2, 3])

In [3]:
N1.shape

(3,)

In [4]:
N1[0]

1

In [5]:
N1[-1]

3

In [19]:
N2=np.array([(11,12,13),[14,15,16],[17,18,19]])
print(N2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [20]:
t=N2.shape
type(t)

tuple

In [21]:
N2[1]

array([14, 15, 16])

In [22]:
N2[0,1]

12

In [23]:
N2[0,1:]

array([12, 13])

In [26]:
N2[1:,1:]

array([[15, 16],
       [18, 19]])

In [37]:
N3=np.array([[(111,112,113),(114,115,116),(117,118,119)],
             [(211,212,213),(214,215,216),(217,218,219)],
             [(311,312,313),(314,315,316),(317,318,319)]])
print(N3)

[[[111 112 113]
  [114 115 116]
  [117 118 119]]

 [[211 212 213]
  [214 215 216]
  [217 218 219]]

 [[311 312 313]
  [314 315 316]
  [317 318 319]]]


In [34]:
N3[0,1:,0:2]

array([[114, 115],
       [117, 118]])

In [39]:
N3[-1,-2,-2]

315

In [45]:
np.zeros([1,2,2,3,4])

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [49]:
np.arange(10,1,-2)

array([10,  8,  6,  4,  2])

In [1]:
import pandas as pd

In [2]:
df=pd.DataFrame({'a':[4,5,6],'b':[7,8,9],'c':[10,11,12]},
                index=[1,2,3])
df

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [3]:
df1=pd.DataFrame([[4,7,10],[5,8,11],[6,9,12]],
                 index=[1,2,3],columns=['a','b','c'])
df1

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [55]:
df['a'][1]=44

In [56]:
df

a  b   c
1  44  7  10
2   5  8  11
3   6  9  12

In [4]:
df2=pd.DataFrame({'a':[4,5,6],'b':[7,8,9],'c':[10,11,12]},
                index=pd.MultiIndex.from_tuples(
                    [('d',1),('d',2),('e',3)],
                    names=['n','v']))
df2

a  b   c
n v          
d 1  4  7  10
  2  5  8  11
e 3  6  9  12

In [5]:
df.head(1)

a  b   c
1  4  7  10

In [6]:
df.tail(1)

a  b   c
3  6  9  12

In [7]:
pd.melt(df)

variable  value
0        a      4
1        a      5
2        a      6
3        b      7
4        b      8
5        b      9
6        c     10
7        c     11
8        c     12

In [8]:
pd.melt(df2)

variable  value
0        a      4
1        a      5
2        a      6
3        b      7
4        b      8
5        b      9
6        c     10
7        c     11
8        c     12

In [9]:
df3=pd.concat([df,df1])
df3

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12
1  4  7  10
2  5  8  11
3  6  9  12

In [10]:
df3['a'][1]

1    4
1    4
Name: a, dtype: int64

In [11]:
pd.concat([df,df2])

a  b   c
1       4  7  10
2       5  8  11
3       6  9  12
(d, 1)  4  7  10
(d, 2)  5  8  11
(e, 3)  6  9  12

In [12]:
pd.concat([df,df1],axis=1)

a  b   c  a  b   c
1  4  7  10  4  7  10
2  5  8  11  5  8  11
3  6  9  12  6  9  12

In [13]:
pd.concat([df,df2],axis=1)

a    b     c    a    b     c
1       4.0  7.0  10.0  NaN  NaN   NaN
2       5.0  8.0  11.0  NaN  NaN   NaN
3       6.0  9.0  12.0  NaN  NaN   NaN
(d, 1)  NaN  NaN   NaN  4.0  7.0  10.0
(d, 2)  NaN  NaN   NaN  5.0  8.0  11.0
(e, 3)  NaN  NaN   NaN  6.0  9.0  12.0

In [16]:
df.sort_values(['a','c'],ascending=False)

a  b   c
3  6  9  12
2  5  8  11
1  4  7  10

In [15]:
df2.sort_values('c',ascending=False)

a  b   c
n v          
e 3  6  9  12
d 2  5  8  11
  1  4  7  10

In [18]:
df['b'].value_counts()

8    1
9    1
7    1
Name: b, dtype: int64